### ISSUE TITLE
API token is readable by guest

### ISSUE THREAD

**Issue by mythz** [gistcafe/hello-rust#1]

**Comment by mythz** [comment]
Please revoke this API token

**Comment by tilpner** [comment]
@mythz ^

**Comment by mythz** [comment]
done, thx

**Comment by gistcafeu** [comment]
@mythz It's not _really_ fixed though. My token was logged at startup, and the logs are public. :)

**Comment by gistcafeu** [comment]
Also, please don't log every user request publicly, it is readable by other users (including IP address and gist content)
